const products=[
{name:'Levo-CM Syrup',cat:'respiratory',label:'Respiratory & Allergy',img:'assets/image1.png',sub:'Pediatric allergy & airway support',comp:'Montelukast Sodium 4 mg + Levocetirizine HCl 2.5 mg',benefits:['Controls allergy and helps prevent airway inflammation','24-hour relief from allergy and asthma symptoms','Relieves sneezing, runny nose and itching'],ind:'Allergic rhinitis, sneezing & runny nose, nasal congestion, pediatric allergies, night-time allergy symptoms.',dose:'Children above 2 years: 5 ml/day or as directed by the physician.'},
{name:'SOIN-D3 Nano Drops',cat:'pediatric',label:'Pediatric & Nutrition',img:'assets/image2.png',sub:'Vitamin D3 800 IU nano drops',comp:'Vitamin D3 800 IU',benefits:['Supports calcium absorption','Promotes bone mineralization','Supports immune function','Essential for growth and development','Nano delivery supports enhanced bioavailability and rapid absorption'],ind:'Vitamin D supplementation and support for healthy growth and bone development.',dose:'Use as directed by a healthcare professional.'},
{name:'Soincold-NS',cat:'respiratory',label:'Respiratory & Allergy',img:'assets/image3.png',sub:'Gentle saline nasal care',comp:'Sodium Chloride Nasal Solution 0.65%',benefits:['Clears nasal congestion','Moisturizes dry nasal passages','Removes dust, allergens and mucus','Suitable for daily use'],ind:'Nasal congestion/blocked nose, dry nasal passages, allergic rhinitis, common cold and sinus discomfort.',dose:'1–2 sprays in each nostril, 2–4 times daily or as directed by the physician.'},
{name:'SoinCold Suspension',cat:'respiratory',label:'Respiratory & Allergy',img:'assets/image4.png',sub:'Cold & fever symptom relief',comp:'Paracetamol 250 mg + Phenylephrine 5 mg + Chlorpheniramine Maleate 2 mg',benefits:['Antipyretic and analgesic support','Helps open blocked nose','Relief from upper respiratory allergy symptoms'],ind:'Common cold, nasal & throat itching, body ache, fever and blocked nose.',dose:'Use only as directed by the physician.'},
{name:'SoinCold-AF Syrup',cat:'respiratory',label:'Respiratory & Allergy',img:'assets/image4.png',sub:'Fast & effective relief from cold & allergies',comp:'Phenylephrine 5 mg + Chlorpheniramine Maleate 2 mg',benefits:['Combines a decongestant and antihistamine','Reduces nasal congestion, sneezing, runny nose and sinus pressure','Helps open blocked nasal passages'],ind:'Common cold, allergic rhinitis, sinus congestion and flu symptoms.',dose:'Use only as directed by the physician.'},
{name:'SoinRash Cream',cat:'dermatology',label:'Dermatology',img:'assets/image5.png',sub:"Baby's comfort & mother's relief",comp:'Zinc Oxide 8.5% + Benzalkonium Chloride 0.1%',benefits:['Zinc oxide helps soothe and heal rash','Benzalkonium chloride provides antiseptic and disinfectant action','Relieves itching and irritation'],ind:'Nappy rashes, skin irritation, itching and mild stinging.',dose:'Apply as directed by a healthcare professional.'},
{name:'SOINPEP Drops',cat:'pediatric',label:'Pediatric & Digestive',img:'assets/image6.png',sub:'Digestive support for infants',comp:'Alpha Amylase 20 mg + Papain 10 mg + Dill Oil 2 mg + Anise Oil 2 mg + Caraway Oil 2 mg',benefits:['Supports carbohydrate digestion','Supports protein digestion','Carminative oils help digestive comfort'],ind:'Infantile colic, indigestion, flatulence/fermentative dyspepsia and post-feed abdominal distention.',dose:'Use as directed by a healthcare professional.'},
{name:'SOINPEP Syrup',cat:'pediatric',label:'Digestive & Nutrition',img:'assets/image7.png',sub:'Dual enzyme support for healthy digestion',comp:'Alpha-Amylase 100 mg + Papain 50 mg',benefits:['Helps digest carbohydrates and protein','Helps relieve indigestion and bloating','Promotes healthy appetite','Supports better nutrient absorption'],ind:'Indigestion, bloating, post-meal fullness and reduced digestive comfort.',dose:'Adults & children above 2 years: 5 ml (1 teaspoonful) twice daily or as directed by the physician.'},
{name:'SOINPEAU Moisturising Soap',cat:'dermatology',label:'Dermatology',img:'assets/image8.png',sub:'Moisture-lock cleansing for lasting softness',comp:'Moisturising cleansing bar',benefits:['Hydrates and soothes skin','Deeply nourishes and softens','Helps prevent dryness','Locks in moisture and supports smooth skin'],ind:'Dry and sensitive skin, dull and dehydrated skin, gentle everyday cleansing.',dose:'Suitable for regular cleansing as appropriate.'},
{name:'SOINPEAU KIDZ Bathing Bar',cat:'pediatric',label:'Pediatric Skin Care',img:'assets/image8.png',sub:'Gentle care for delicate skin',comp:'Kids bathing bar formulated for gentle cleansing',benefits:['Keeps delicate skin soft and moisturized','Helps retain skin moisture','Soothes sensitive skin','Free from harsh chemicals, parabens, sulfates and artificial colors'],ind:"Baby's delicate skin and daily cleansing for sensitive skin.",dose:'For regular external cleansing.'},
{name:'EARSOIN-AB Drops',cat:'ear',label:'Ear Care',img:'assets/image9.png',sub:'Triple-action formula for ear discharge',comp:'Ofloxacin + Clotrimazole + Lignocaine Hydrochloride',benefits:['Antibacterial action','Antifungal action','Topical pain relief'],ind:'Otitis media, bacterial infections, fungal infections and mixed infections.',dose:'Use only as directed by the physician.'},
{name:'EarsOin Dewaxing Drops',cat:'ear',label:'Ear Care',img:'assets/image9.png',sub:'Scientific approach to removing wax',comp:'Benzocaine + Chlorbutol + Turpentine Oil + Paradichlorobenzene',benefits:['Helps dissolve and clear ear wax','Provides local soothing relief','Supports easier ear examination'],ind:'Prior to ear surgery, dissolve ear wax, ear examination and relief of ear discomfort.',dose:'Use only as directed by the physician.'},
{name:'Levo-C Tablets',cat:'respiratory',label:'Respiratory & Allergy',img:'assets/image10.png',sub:'Levocetirizine HCl IP 5 mg',comp:'Levocetirizine HCl IP 5 mg',benefits:['Antihistamine therapy for conventional allergies','Helps reduce bronchoconstriction and airway obstruction'],ind:'Seasonal allergic rhinitis, rhinitis associated with asthma, perennial allergic rhinitis, atopic eczema and acute allergic reactions.',dose:'Use only as directed by the physician.'},
{name:'Levo-CM Tablets',cat:'respiratory',label:'Respiratory & Allergy',img:'assets/image11.png',sub:'Dual-action allergy and asthma support',comp:'Montelukast Sodium 10 mg + Levocetirizine HCl 5 mg',benefits:['Levocetirizine helps block histamine-mediated allergy symptoms','Montelukast inhibits leukotriene activity','Supports prevention of exercise-induced bronchoconstriction'],ind:'Allergic rhinitis, chronic idiopathic urticaria and prophylaxis/chronic treatment of asthma.',dose:'Use only as directed by the physician.'},
{name:'Tansoin Ultra Cream',cat:'dermatology',label:'Dermatology',img:'assets/image12.png',sub:'Powerful actives for visible skin results',comp:'Tranexamic + Glutathione + Kojic Acid + Alpha Arbutin + Mulberry Extracts + SPF 40 actives',benefits:['Targets melasma and pigmentation','Supports even-looking skin tone','Helps with age/dark spots and blemishes','Provides broad-spectrum sun protection'],ind:'Hyperpigmentation, melasma, age/dark spots, blemishes and sun tan.',dose:'Apply on clean, dry skin at night or as directed.'},
{name:'SOINPEAU ZIT Bar',cat:'dermatology',label:'Dermatology',img:'assets/image13.png',sub:'Acne cleansing bar',comp:'Zinc PCA + Allantoin + Manuca Oil',benefits:['Zinc PCA supports acne-prone skin','Allantoin helps remove dead cells in acne-affected areas','Manuca Oil provides a healing effect'],ind:'Acne-prone skin and cleansing support.',dose:'For external cleansing use.'},
{name:'SOINPEAU-EXFO Soap',cat:'dermatology',label:'Dermatology',img:'assets/image14.png',sub:'Deep cleanse, deep care',comp:'Salicylic Acid + Triclosan + Tea Tree Oil',benefits:['Exfoliates dead skin cells and helps unclog pores','Antibacterial cleansing support','Soothes skin and helps reduce redness'],ind:'Acne-prone skin, oily skin, bacterial & fungal skin infections and body odor control.',dose:'For external cleansing use.'},
{name:'SOINPEAU-GLO Soap',cat:'dermatology',label:'Dermatology',img:'assets/image14.png',sub:'Skin radiance cleansing bar',comp:'Kojic Acid + L-Glutathione + Glycolic Acid',benefits:['Helps reduce the appearance of dark spots and hyperpigmentation','Supports skin radiance','Gently exfoliates and improves texture'],ind:'Uneven skin tone & tan, dark spots & sun damage, acne marks & dullness, fine lines and early signs of aging.',dose:'For external cleansing use.'},
{name:'Tansoin-500 Tablets',cat:'dermatology',label:'Dermatology',img:'assets/image15.png',sub:'Tranexamic Acid 500 mg',comp:'Tranexamic Acid IP 500 mg',benefits:['Helps inhibit melanin synthesis pathways','Used as a targeted treatment approach in melasma management'],ind:'Melasma, acne scars, UV-induced hyperpigmentation and post-inflammatory hyperpigmentation.',dose:'Prescription medicine — use only under physician direction.'},
{name:'Mane Marvel Tablets',cat:'hair',label:'Hair Nutrition',img:'assets/image16.png',sub:'Comprehensive hair nutrition',comp:'Biotin + Niacinamide + Zinc + Calcium Pantothenate + Sodium Selenate + Amino Acids and supportive micronutrients',benefits:['Strengthens hair roots','Supports healthy hair growth','Improves hair thickness and density','Provides antioxidant support','Supports keratin formation'],ind:'Nutritional hair fall, telogen effluvium, weak & brittle hair and canities (premature greying).',dose:'1 tablet per day or as directed by the physician.'},
{name:'Lulisoin-Pro Cream',cat:'dermatology',label:'Anti-Fungal Care',img:'assets/image17.png',sub:'Fast relief from fungal infection & itching',comp:'Luliconazole 1% + Pramoxine Hydrochloride 1%',benefits:['Targets fungal infection','Provides rapid itch relief','Helps reduce redness and discomfort','Dual-action approach may support treatment compliance'],ind:'Tinea corporis (ringworm), tinea cruris (jock itch) and tinea pedis (athlete’s foot).',dose:'Apply a thin layer on affected areas once daily for 2–4 weeks or as directed by the physician.'},
{name:'PEAUSOR-TOFA',cat:'specialty',label:'Specialty Care',img:'assets/image18.png',sub:'Tofacitinib 5 mg tablets',comp:'Tofacitinib 5 mg',benefits:['JAK pathway inhibition','Targets inflammatory signaling','Positioned for systemic inflammatory dermatologic disease management'],ind:'Inflammatory dermatosis, vitiligo vulgaris, atopic dermatitis and psoriasis.',dose:'Prescription medicine — use only under specialist/physician direction.'},
{name:'Peausor-MXT',cat:'specialty',label:'Specialty Care',img:'assets/image19.png',sub:'Methotrexate 2.5 mg / 5 mg tablets',comp:'Methotrexate 2.5 mg / 5 mg',benefits:['Folate antagonist mechanism','Slows disease progression','Reduces inflammation','Used in psoriasis and autoimmune disease management'],ind:'Psoriasis and other autoimmune disorders.',dose:'Prescription medicine requiring physician supervision and monitoring.'}
];
const labels={all:'All',respiratory:'Respiratory',pediatric:'Pediatric & Digestive',dermatology:'Dermatology',ear:'Ear Care',hair:'Hair Nutrition',specialty:'Specialty'};
const grid=document.querySelector('#grid'),filters=document.querySelector('#filters'),search=document.querySelector('#search'),empty=document.querySelector('#empty');let active='all';
Object.entries(labels).forEach(([k,v])=>{const b=document.createElement('button');b.textContent=v;b.dataset.filter=k;if(k==='all')b.classList.add('active');b.onclick=()=>{active=k;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render()};filters.appendChild(b)});
function render(){const q=search.value.toLowerCase().trim();const list=products.filter(p=>(active==='all'||p.cat===active)&&(`${p.name} ${p.comp} ${p.ind} ${p.label}`.toLowerCase().includes(q)));grid.innerHTML=list.map((p,i)=>`<article class="product" data-i="${products.indexOf(p)}"><div class="product-media"><img loading="lazy" src="${p.img}" alt="${p.name}"></div><div class="product-copy"><span class="tag">${p.label}</span><h3>${p.name}</h3><p>${p.comp}</p><div class="more"><span>View product details</span><b>→</b></div></div></article>`).join('');empty.hidden=list.length>0;grid.querySelectorAll('.product').forEach(el=>el.onclick=()=>openProduct(+el.dataset.i))}
search.addEventListener('input',render);render();
const modal=document.querySelector('#modal');function openProduct(i){const p=products[i];mImg.src=p.img;mImg.alt=p.name;mCat.textContent=p.label;mName.textContent=p.name;mSub.textContent=p.sub;mComp.textContent=p.comp;mBenefits.innerHTML=p.benefits.map(x=>`<li>${x}</li>`).join('');mInd.textContent=p.ind;mDose.textContent=p.dose;doseWrap.hidden=!p.dose;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('open'))document.querySelector('[data-close]').click()});
document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{active=b.dataset.jump;filters.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x.dataset.filter===active));render();document.querySelector('#portfolio').scrollIntoView({behavior:'smooth'})});
const menu=document.querySelector('.menu'),nav=document.querySelector('.nav nav');menu.onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>obs.observe(x));
